# =============================================================================
# OpenMP autodetect — mirrors ThirdParty/Parallel/Cmake/openmp.cmake's find_package(OpenMP).
#
# CMake's OpenMP::OpenMP_CXX imported target transparently supplies whatever
# compile/link flags the platform's OpenMP runtime needs. Bazel has no
# find_package() equivalent, so this repository rule probes for the same
# thing directly:
#   - Linux:   plain -fopenmp usually suffices (GCC, or Clang with
#              libomp-dev installed such that the system linker resolves it).
#   - macOS:   Apple Clang has no built-in OpenMP runtime; needs Homebrew's
#              libomp (`brew install libomp`, matching openmp.cmake's own
#              "To enable OpenMP on macOS" guidance) via
#              -Xpreprocessor -fopenmp -I<libomp>/include, linked with
#              -L<libomp>/lib -lomp.
#   - Windows: MSVC ships OpenMP in-box via /openmp; not probed (mirrors
#              svml_configure.bzl's Windows-always-needs-svml assumption —
#              no local toolchain available in this repo to probe against).
#
# Always succeeds (writes OPENMP_FOUND=False + empty flag lists when nothing
# works) so loading this repo never breaks a build that doesn't use the
# OpenMP backend — exactly like svml_configure.bzl's unconditional per-tier
# probe. The fail-fast behavior for an *actual* --define parallel_backend=openmp
# build with no OpenMP available happens separately, via the :openmp_check
# target this rule also generates (same "fail only when actually depended on"
# pattern as sleef_configure.bzl's :sleef target).
# =============================================================================

def _is_windows(repository_ctx):
    n = repository_ctx.os.name.lower()
    return n == "windows" or n.startswith("win")

def _is_macos(repository_ctx):
    n = repository_ctx.os.name.lower()
    return n.startswith("mac") or n.startswith("darwin")

def _cxx(repository_ctx):
    cxx = repository_ctx.os.environ.get("CXX", "") or repository_ctx.os.environ.get("CC", "")
    cxx = cxx.strip().strip("\"'")
    if cxx:
        return cxx
    for candidate in ("c++", "clang++", "g++"):
        w = repository_ctx.which(candidate)
        if w:
            return str(w)
    return ""

_PROBE_SRC = """#include <omp.h>
int main() {
  int n = omp_get_max_threads();
  #pragma omp parallel for
  for (int i = 0; i < n; ++i) {}
  return 0;
}
"""

_LIBOMP_CANDIDATE_PREFIXES = [
    "/opt/homebrew/opt/libomp",  # Apple Silicon Homebrew
    "/usr/local/opt/libomp",  # Intel Homebrew
]

def _try_compile_link(repository_ctx, cxx, copts, linkopts):
    cmd = [cxx, "-std=c++17"] + copts + ["-c", "probe.cpp", "-o", "probe_openmp.o"]
    r = repository_ctx.execute(cmd, quiet = True)
    if r.return_code != 0:
        return False
    cmd = [cxx] + copts + ["probe.cpp", "-o", "probe_openmp"] + linkopts
    r = repository_ctx.execute(cmd, quiet = True)
    return r.return_code == 0

def _find_libomp_prefix(repository_ctx):
    env_override = repository_ctx.os.environ.get("LIBOMP_PATH", "").strip()
    candidates = ([env_override] if env_override else []) + _LIBOMP_CANDIDATE_PREFIXES
    for prefix in candidates:
        if prefix and repository_ctx.path(prefix + "/include/omp.h").exists:
            return prefix
    return None

def _probe_unix(repository_ctx):
    cxx = _cxx(repository_ctx)
    if not cxx:
        return (False, [], [])

    repository_ctx.file("probe.cpp", _PROBE_SRC)

    # Plain -fopenmp first (GCC anywhere; Clang on Linux with libomp-dev installed).
    if _try_compile_link(repository_ctx, cxx, ["-fopenmp"], ["-fopenmp"]):
        return (True, ["-fopenmp"], ["-fopenmp"])

    if _is_macos(repository_ctx):
        prefix = _find_libomp_prefix(repository_ctx)
        if prefix:
            copts = ["-Xpreprocessor", "-fopenmp", "-I" + prefix + "/include"]
            linkopts = ["-L" + prefix + "/lib", "-lomp"]
            if _try_compile_link(repository_ctx, cxx, copts, linkopts):
                return (True, copts, linkopts)

    return (False, [], [])

def _write_config(repository_ctx, found, copts, linkopts):
    lines = [
        "# Generated by //bazel:openmp_configure.bzl — do not edit.",
        "OPENMP_FOUND = %s" % found,
        "OPENMP_COPTS = %r" % copts,
        "OPENMP_LINKOPTS = %r" % linkopts,
    ]
    repository_ctx.file("config.bzl", "\n".join(lines) + "\n")

_SETUP_HINT_UNIX = (
    "OpenMP (--define parallel_backend=openmp / --config=openmp) needs a working " +
    "OpenMP toolchain. On Linux: install libomp-dev (Clang) or use GCC (OpenMP " +
    "built in). On macOS: `brew install libomp` (Apple Clang has no built-in " +
    "OpenMP runtime) — see ThirdParty/Parallel/Cmake/openmp.cmake for the same " +
    "guidance CMake gives. Re-run the Bazel build afterwards."
)

_MISSING_BUILD_FILE = """\
package(default_visibility = ["//visibility:public"])

genrule(
    name = "openmp_missing",
    outs = ["openmp_missing.cc"],
    cmd = "echo OPENMP_NOT_FOUND_SEE_MESSAGE_ABOVE >&2; exit 1",
    message = {message},
)

cc_library(
    name = "openmp_check",
    srcs = [":openmp_missing"],
)
""".format(message = repr(_SETUP_HINT_UNIX))

_FOUND_BUILD_FILE = """\
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "openmp_check",
)
"""

def _openmp_configure_impl(repository_ctx):
    if _is_windows(repository_ctx):
        # MSVC ships OpenMP via /openmp; not probed (see module docstring).
        _write_config(repository_ctx, True, ["/openmp"], [])
        repository_ctx.file("BUILD.bazel", _FOUND_BUILD_FILE)
        return

    found, copts, linkopts = _probe_unix(repository_ctx)
    _write_config(repository_ctx, found, copts, linkopts)
    repository_ctx.file("BUILD.bazel", _FOUND_BUILD_FILE if found else _MISSING_BUILD_FILE)

openmp_configure = repository_rule(
    implementation = _openmp_configure_impl,
    local = True,
    environ = [
        "CXX",
        "CC",
        "PATH",
        "LIBOMP_PATH",
    ],
)
